local set = vim.keymap.set
local del = vim.keymap.del

del("n", "<C-w><C-d>")
del("n", "<C-w>d")

set({ "n", "i", "v" }, "<C-s>", "<Esc><cmd>w<CR>", { desc = "[S]ave buffer" })
set("n", "<A-j>", "<cmd>move +1<CR>==", { desc = "Move block down" })
set("n", "<A-k>", "<cmd>move -2<CR>==", { desc = "Move block up" })
set("n", "<C-d>", "<C-d>zz", { desc = "Page down" })
set("n", "<C-u>", "<C-u>zz", { desc = "Page up" })
set("n", "<C-w><C-d>", "<cmd>bp<bar>sp<bar>bn<bar>bd<CR>", { desc = "Close current buffer (:bd) while keeping window" })
set("n", "<F10>", "<cmd>lua require'dap'.step_into()<CR>", { desc = "Debug step into" })
set("n", "<F11>", "<cmd>lua require'dap'.step_out()<CR>", { desc = "Debug step out" })
set("n", "<F1>", "<cmd>lua require'dapui'.eval()<CR>", { desc = "Debug evaluate" })
set("n", "<F4>", "<cmd>lua require'dapui'.toggle()<CR>", { desc = "Debug toggle" })
set("n", "<F5>", "<cmd>lua require'dap'.toggle_breakpoint()<CR>", { desc = "Debug toggle breakpoint" })
set("n", "<F6>", "<cmd>lua require'dap'.continue()<CR>", { desc = "Debug continue" })
set("n", "<F9>", "<cmd>lua require'dap'.step_over()<CR>", { desc = "Debug step over" })
set("n", "<S-tab>", "<cmd>bprevious<CR>", { desc = "Navigate tab left" })
set("n", "<Tab>", "<cmd>bn<CR>", { desc = "Navigate tab right" })
set("n", "<leader>%", "<C-W><C-v>", { desc = "[W]indow [v]ertical split" })
set("n", "<leader>-", "<cmd>vertical resize -30<CR>", { desc = "Decrease window horizontal size" })
set("n", "<leader>=", "<cmd>vertical resize +30<CR>", { desc = "Increase window horizontal size" })
set("n", "<leader>a", "ggVG", { desc = "Select all" })
set("n", "<leader>bt", "<cmd>BlamerToggle<CR>", { desc = "[B]lame [T]oggle" })
set("n", "<leader>wd", "<cmd>w<bar>%bd<bar>e#<bar>bd#<CR>", { desc = "Close all buffers except current one" })
set("n", "<leader>wo", "<cmd>lua print('use CTRL-w CTRL-o instead')<CR>")
set("n", "<leader>wr", "<C-W><C-r>", { desc = "[W]indow [r]otate" })
set("n", "S-Y", "y$", { desc = "[Y]ank to end of line" })
set("n", "[d", "<cmd>Lspsaga diagnostic_jump_prev<CR>", { desc = "Next diagnostic" })
set("n", "]d", "<cmd>Lspsaga diagnostic_jump_next<CR>", { desc = "Previous diagnostic" })
set("n", "x", '"_x', { desc = "Remove char without copying to clipboard" })
set("n", '<leader>"', "<C-W><C-s>", { desc = "[W]indow horizontal [s]plit" })
set("v", "<A-j>", ":m '>+1<CR>gv=gv", { desc = "Move line down" })
set("v", "<A-k>", ":m '<-2<CR>gv=gv", { desc = "Move line up" })
set("x", "<leader>p", '"_dP', { desc = "[P]aste without replacing current register contents" })
