local gh = "https://github.com/"

vim.pack.add({
    { src = gh .. "APZelos/blamer.nvim" },
    { src = gh .. "ThePrimeagen/harpoon", version = "harpoon2" },
    { src = gh .. "akinsho/bufferline.nvim" },
    { src = gh .. "catgoose/nvim-colorizer.lua" },
    { src = gh .. "echasnovski/mini.icons" },
    { src = gh .. "folke/trouble.nvim" },
    { src = gh .. "folke/which-key.nvim" },
    { src = gh .. "haydenmeade/neotest-jest" },
    { src = gh .. "jay-babu/mason-null-ls.nvim" },
    { src = gh .. "junegunn/fzf", build = "fzf#install" },
    { src = gh .. "kevinhwang91/nvim-bqf" },
    { src = gh .. "leoluz/nvim-dap-go" },
    { src = gh .. "lewis6991/gitsigns.nvim" },
    { src = gh .. "mfussenegger/nvim-dap" },
    { src = gh .. "mrjones2014/smart-splits.nvim", build = "./kitty/install-kittens.bash" },
    { src = gh .. "neovim/nvim-lspconfig" },
    { src = gh .. "ntpeters/vim-better-whitespace" },
    { src = gh .. "nvim-lua/plenary.nvim" },
    { src = gh .. "nvim-lualine/lualine.nvim" },
    { src = gh .. "nvim-neotest/neotest" },
    { src = gh .. "nvim-neotest/neotest-go" },
    { src = gh .. "nvim-neotest/neotest-plenary" },
    { src = gh .. "nvim-neotest/neotest-vim-test" },
    { src = gh .. "nvim-neotest/nvim-nio" },
    { src = gh .. "nvim-telescope/telescope-fzf-native.nvim", build = "make" },
    { src = gh .. "nvim-telescope/telescope.nvim" },
    { src = gh .. "nvim-tree/nvim-web-devicons" },
    { src = gh .. "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
    { src = gh .. "nvimtools/none-ls.nvim" },
    { src = gh .. "olimorris/neotest-phpunit" },
    { src = gh .. "rafamadriz/friendly-snippets" },
    { src = gh .. "rcarriga/nvim-dap-ui" },
    { src = gh .. "rebelot/kanagawa.nvim" },
    { src = gh .. "rhydianjenkins/nvim-highlight" },
    { src = gh .. "rhydianjenkins/symfonyutils" },
    { src = gh .. "rouge8/neotest-rust" },
    { src = gh .. "saghen/blink.cmp" },
    { src = gh .. "saghen/blink.lib" },
    { src = gh .. "stevearc/oil.nvim" },
    { src = gh .. "vim-test/vim-test" },
    { src = gh .. "williamboman/mason-lspconfig.nvim" },
    { src = gh .. "williamboman/mason.nvim" },
})
