vim.g.vdebug_options = {
    port               = 9009,
    timeout            = 20,
    server             = '',
    on_close           = 'stop',
    break_on_open      = 0,
    ide_key            = 'PHPSTORM',
    debug_window_level = 0,
    debug_file_level   = 0,
    debug_file         = '',
    path_maps          = { ['/var/basekit'] = '/var/www/basekit' },
    watch_window_style = 'expanded',
    marker_default     = '⬦',
    marker_closed_tree = '▸',
    marker_open_tree   = '▾',
    sign_breakpoint    = '▷',
    sign_current       = '▶',
    continuous_mode    = 1,
    simplified_status  = 1,
    layout             = 'vertical',
}

vim.g.vdebug_keymap = {
    run = '<F5>',
    run_to_cursor = '<F9>',
    step_over = '<F2>',
    step_into = '<F3>',
    step_out = '<F4>',
    close = '<F6>',
    detach = '<F7>',
    set_breakpoint = '<F10>',
    get_context = '<F11>',
    eval_under_cursor = '<F12>',
    eval_visual = '<Leader>e',
}
