name: Code Quality

on: [push]

jobs:

  Stylua:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Running stylua
      uses: JohnnyMorganz/stylua-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version: latest
        args: --check .

  Luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Running luacheck
        uses: lunarmodules/luacheck@v0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --config nvim/.luacheckrc .
