name: Nix

on:
  push:
    paths:
      - nix/**

jobs:

  Check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/cache@v3
      with:
        path: /nix/store
        key: ${{ runner.os }}-nix-${{ hashFiles('flake.nix', 'system/configuration.nix', 'user/home.nix') }}
    - run: nix flake check
      working-directory: ./nix
